### ISSUE TITLE
Google Vertex AI integration

### ISSUE THREAD

**Issue by silvanocerza** [deepset-ai/haystack-core-integrations#115]
## Summary and motivation

This already mostly implemented but I'm creating this issue to track the remaining work.

## Checklist

If the request is accepted, ensure the following checklist is complete before closing this issue.

- [x] The code was merged in the `main` branch
- [x] https://github.com/deepset-ai/haystack-core-integrations/issues/155
- [x] There is a Github workflow running the tests for the integration nightly and at every PR
- [x] A label named like `integration:<your integration name>` has been added to this repo
- [x] The [labeler.yml](https://github.com/deepset-ai/haystack-core-integrations/blob/main/.github/labeler.yml) file has been updated
- [x] The package has been released on PyPI
- [x] #120
- [x] The integration has been listed in the [Inventory section](https://github.com/deepset-ai/haystack-core-integrations#inventory) of this repo README
- [x] #117
- [x] #116

**Comment by TuanaCelik** [comment]
@silvanocerza @masci - since we're also creating an integration directly to Gemini, and as far as we understand this integration has been only to access Gemini models via VertexAI/GCP, does it make more sense to name the generator `VertexAIGeminiGenerator` in this integration instead of `GeminiGenerator`? 

-- question from @deepset-ai/devrel collectively

**Comment by TuanaCelik** [comment]
@silvanocerza @dfokina we've created an issue for docs and assigned Daria for now, if that's helpful to track. But I think you should be in touch about the naming of the components here as there's a separate similar integration coming for Makersuite which means the `GeminiGenerator` might change names
