### ISSUE TITLE
How to reconnect to a PGVector document store?

### ISSUE THREAD

**Issue by phiweger** [deepset-ai/haystack-core-integrations#1168]
When some time passes, the document store connected to Postgres loses its connection. Is there a way to reconnect without having to reinitialize the store?

Thanks!

**Comment by lattaai4** [comment]
Hello, I tried to fix the issue

This is what I did:

To fix the issue of lost connections in the PostgreSQL document store, we'll add a retry mechanism that attempts to reconnect without reinitializing the entire store. This involves modifying the _create_connection method and adding a new _ensure_connection method.

I also created pull request: https://github.com/deepset-ai/haystack-core-integrations/pull/1169


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.
