### ISSUE TITLE
chore: Update all generator integrations to use new generic callable (de)serializers for their callback handlers

### ISSUE THREAD

**Issue by vblagoje** [deepset-ai/haystack-core-integrations#415]
We have migrated all the (de)serialize callback handlers in Haystack 2.x to use the new generic utils methods serialize_callable and deserialize_callable. Now, we need to do that for all generators in [haystack-core-integrations](https://github.com/deepset-ai/haystack-core-integrations). The best time to migrate these will likely be after the next Haystack beta is released.

**Comment by masci** [comment]
@ZanSara I think the two linked PRs do something different - this issue was open to keep track of the changes needed after replacing `haystack.components.generators.utils.serialize_callback_handler` in `main` with `haystack.utils.callable_serialization.serialize_callable`. The course of action I imagine would involve a new beta release to ship `serialize_callback_handler` and change the integrations (or merging your current PRs but change the integration again later after we release the change). In that sense, you should add `ollama` to the list of integrations that we need to change.
